### ISSUE TITLE
It is great that your app is hitting google play store. Can you develop wider range of vibration duration setting?

### ISSUE THREAD

**Issue by mengkelee** [lwis/miband-notifier#24] opened 2015-05-31 19:43 UTC
If you have time please try the twisted miband app with notify that one has a more user-friendly setting options. What would be good is that the vibration can be set to be felt the difference in duration. So with some notification like hourly time notify, I don't have check the led to tell what it is for. Right now, I need always to check the lights because it only vibrate either  twice or 4 times(among four settings) and the duration setting range is not wide enough to be able to tell the difference from long to short.

Please support android 4.4.4, because that is what Mi mobiles are using with MIUI. Millions of Chinese fans are asking in the Xiaomi Chinese bbs to be able to use your app. But they cannot since using the android 4.4.4 .

Your app could easily hit millions on google store if you can get things right because Mi band is the second best-selling smart band around the world and your app just made the tiger fly. Because for some reason, Xiaomi chose not to be open minded with their official app. Eventually this could be a good app with a price less than 2 dollars in the store, I would buy it.

**Comment by mengkelee** [comment] 2015-05-31 20:01
Here is the link:    http://en.miui.com/thread-53761-1-1.html

**Comment by itsmepetrov** [comment] 2015-05-31 20:15
+1

**Comment by lwis** [comment] 2015-06-01 06:31
Without putting the band into high power mode (which takes a few seconds to
respond) the vibration duration is inconsistent, owing to the latency
caused by BLE.

I may change the vibration to be the short double or the single long,
however.

**Comment by lwis** [comment] 2015-06-01 06:34
I am considering lowering the version to 4.4.4, however this would need
testing which I am unable to do.

The BLE stack changed dramatically in Lollipop so it may be hugely
incompatible.

I'm not interested in selling the app, due to the responsibilities I am
unable to guarantee.

**Comment by lwis** [comment] 2015-06-02 17:54
@mengkelee Here's a build with the minimum sdk set to 16, let me know if you have any issues. http://cl.ly/3b0H22463H3P

**Comment by ingbrzy** [comment] 2015-06-02 18:04
Working well on 4.4.4 MIUIv6..! thank you...!

**Comment by lwis** [comment] 2015-06-02 18:09
@ingbrzy Excellent, I'll lower the SDK to 19 for now. If anyone on 16, 17, 18 can confirm that's working, please let me know!

**Comment by ingbrzy** [comment] 2015-06-02 18:11
hm.. wait.. testing works.. but if any notification arrived, its not working... same issue was on 4.4 for this app https://play.google.com/store/apps/details?id=com.mc.mibandfree and its fixed now..

**Comment by lwis** [comment] 2015-06-02 18:13
@ingbrzy Are you able to provide logcat logs with a debug build? http://cl.ly/3l2n2B1J1H22

**Comment by ingbrzy** [comment] 2015-06-02 18:24
yep.. here it is https://mega.co.nz/#!LpQ1yKiA!MHG1LP5xOrEYOfrPKuV5opma84eupCbcgHpCXLGck5o

**Comment by ingbrzy** [comment] 2015-06-02 18:32
btw.. how works that..?     
```
<string name="user_not_present">Non interactive</string>
```

**Comment by lwis** [comment] 2015-06-02 18:33
Lollipop only, and even then not all devices support it.

**Comment by lwis** [comment] 2015-06-02 18:49
@ingbrzy http://cl.ly/0w2m0d2n1E1D - This build resolves all the issues I could find with 19 incompatibilites.

**Comment by ingbrzy** [comment] 2015-06-02 18:56
After installation it opens this app url
![screenshot_2015-06-02-20-51-34](https://cloud.githubusercontent.com/assets/1762519/7944196/8b9e38bc-0969-11e5-856f-91b5015883e0.png)

MiBand MAC address is not complete and has to be added manually
![screenshot_2015-06-02-20-52-06](https://cloud.githubusercontent.com/assets/1762519/7944201/8e5e03e8-0969-11e5-9b0a-5b31a38345b3.png)


anyway, still no vibrations/colors after new apps notifications....

**Comment by lwis** [comment] 2015-06-02 19:01
I've just fixed the issue with the Play Store opening, I didn't notice that from a previous PR.

The MAC address won't be prefilled, on some devices it will find the bonded device automatically.

Hmm, no crashes? It's very difficult for me to debug without a 4.4.4 device.

**Comment by mengkelee** [comment] 2015-06-03 13:00
Do you wanna me to try. I have a Mi 4.  I use the other notify(free/charge) one on Mi 4(android 4.4.4). It was working alright. It doesn't have any settings whatsoever made it hard to catch the LED lights.

**Closed** 2015-07-27 16:05 UTC
